// Static receiver list for dyatlov map maker
// Manually curated from multiple SDR lists
// Licensed under GPLv3+
// File generation timestamp: Wed Dec 31 02:00:00 2025

var static_rx =
[
    {
        "name":"LF/MF/HF Wideband NovaSDR, Heppen, Belgium",
        "url":"http://websdr.heppen.be/?frequency=10000000&modulation=AM",
        "gps":"(51.0833,5.1667)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 mk2",
        "loc":"Heppen, Belgium",
        "sw_version":"NovaSDR",
        "antenna":"54 m inverted L",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF Wideband NovaSDR, Bisag, Croatia",
        "url":"http://9a7aof.ddns.net:8905/?frequency=10000000&modulation=AM",
        "gps":"(46.0340,16.2791)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 mk2",
        "loc":"Bisag, Croatia",
        "sw_version":"NovaSDR",
        "antenna":"Dipole for 80m",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF Wideband NovaSDR, Gillonnay, France",
        "url":"http://linkz.ddns.net:8088/?frequency=10000000&modulation=AM",
        "gps":"(45.3931,5.2852)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 mk2",
        "loc":"Gillonnay, France",
        "sw_version":"NovaSDR",
        "antenna":"80m skywire loop",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"MF/HF/VHF WEBSDR, Lamia, Greece",
        "url":"http://sv1cmg.no-ip.org/?tune=1575am",
        "gps":"(38.8960,22.4743)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Lamia, Greece",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"MF/ WEBSDR, Sparta, Greece",
        "url":"http://sv3gcb.ddns.net:8905/?tune=729am",
        "gps":"(36.9804,22.4420)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Sparta, Greece",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF Wideband NovaSDR, Sardinia Perfugas, Italy",
        "url":"http://sardinia-sdr.ddns.net/?frequency=10000000&modulation=AM",
        "gps":"(40.8124,8.9622)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Sardinia Perfugas, Italy",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"HF Wideband NovaSDR, Sardinia Perfugas, Italy",
        "url":"http://sardinia-sdr.ddns.net:8073/?frequency=10000000&modulation=AM",
        "gps":"(40.8154,8.9322)",
        "bands":"4800000-12800000",
        "users_max":"800",
        "sdr_hw":"RX-888 mk2",
        "loc":"Sardinia Perfugas, Italy",
        "sw_version":"NovaSDR",
        "antenna":"54 m inverted L",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"0-29 MHz WebSDR, University of Twente, Enschede, Netherlands",
        "url":"http://websdr.ewi.utwente.nl:8901/?tune=198am",
        "gps":"(52.2381,6.8577)",
        "bands":"0-29160000",
        "users_max":"800",
        "sdr_hw":"WebSDR / custom, high-performance GPU-based setup",
        "loc":"University of Twente, Enschede, Netherlands",
        "sw_version":"WebSDR",
        "antenna":"Mini-Whip",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"OpenWebRX, Gugaron, India",
        "url":"https://websdr.vu2tum.com/#freq=846000,mod=am,sql=-150",
        "gps":"(28.6011,77.0298)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various OpenWebRX quadrature sampling sources.",
        "loc":"Gugaron, India",
        "sw_version":"OpenWebRX",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"OpenWebRX, Bangalore, India",
        "url":"https://rf.siritech.net/#freq=612000,mod=am,sql=-150",
        "gps":"(12.9259,77.6104)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various OpenWebRX quadrature sampling sources.",
        "loc":"Bangalore, India",
        "sw_version":"OpenWebRX",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"2-16 MHz WebSDR, Silec, Poland",
        "url":"http://websdr.printf.cc:8901/?tune=11175usb",
        "gps":"(54.1605231,21.5543704)",
        "bands":"0-30000000",
        "users_max":"20",
        "sdr_hw":"WebSDR / multiple RTL-SDR dongles with converter",
        "loc":"Silec, Poland",
        "sw_version":"WebSDR",
        "antenna":"30m random wire",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"HF Wideband NovaSDR, Cherepovets, Russia",
        "url":"http://websdr.ru/?frequency=10000000&modulation=USB",
        "gps":"(59.10,37.96)",
        "bands":"0-30000000",
        "sdr_hw":"WebSDR / RTL-SDR and Afedri",
        "loc":"Cherepovets, Russia",
        "sw_version":"NovaSDR",
        "antenna":"City-Windom CW80100",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"Funkclub Schlössli - HB9RE - DMR2282157 (VHF)| Bodenberg, Switzerland",
        "url":"http://hb9re.ddns.net:8083/?f=10000.00amz7&1hz",
        "gps":"(47.1541,7.9233)",
        "bands":"98304000-147456000",
        "users_max":"13",
        "sdr_hw":"Web-888",
        "loc":"Bodenberg, Switzerland",
        "sw_version":"Web888",
        "antenna":"Diamond D-303",
        "snr":"12,12",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF WEBSDR, Bedford, United Kingdom",
        "url":"http://remoteradio.changeip.org:8073/?tune=648am",
        "gps":"(52.0833,-0.5000)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"WebSDR fed by Direct Sampling RTLSDRs",
        "loc":"Bedford, United Kingdom",
        "sw_version":"WebSDR",
        "antenna":"Loop Antennas.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF WEBSDR, Grimsby, United Kingdom",
        "url":"http://grimsbysdr.ddns.net:8073/?tune=198am",
        "gps":"(53.5417,-0.0833)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"WebSDR fed by Direct Sampling RTLSDRs",
        "loc":"Grimsby, United Kingdom",
        "sw_version":"WebSDR",
        "antenna":"Loop Antennas.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Dalgety Bay, Scotland, United Kingdom",
        "url":"https://m9psy.tunnel.ubersdr.org/?freq=1000000&mode=am&bwl=-5000&bwh=5000&zoom_freq=1000000&zoom_bw=100.0",
        "gps":"(56.0403,-3.3554)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 Direct Sampling SDR.",
        "loc":"Dalgety Bay, Scotland, United Kingdom",
        "sw_version":"UberSDR",
        "antenna":"end fed long wire",
        "snr":"22,22",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Wessex, United Kingdom",
        "url":"http://wessex.zapto.org:8035/?freq=1000000&mode=am&bwl=-5000&bwh=5000&zoom_freq=1000000&zoom_bw=100.0",
        "gps":"(50.7401,-2.6307)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 Direct Sampling SDR.",
        "loc":"Wessex, United Kingdom",
        "sw_version":"UberSDR",
        "antenna":"terminated delta loop",
        "snr":"22,22",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Fuerteventura, Canary Islands",
        "url":"https://ea8-df4ue.tunnel.ubersdr.org/?freq=1000000&mode=am&bwl=-5000&bwh=5000&zoom_freq=1000000&zoom_bw=100.0",
        "gps":"(28.6459,-13.9051)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 Direct Sampling SDR.",
        "loc":"Fuerteventura, Canary Islands",
        "sw_version":"UberSDR",
        "antenna":"multiband dipole",
        "snr":"22,22",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Graz, Austria",
        "url":"https://oe6add.tunnel.ubersdr.org/?freq=1000000&mode=am&bwl=-5000&bwh=5000&zoom_freq=1000000&zoom_bw=100.0",
        "gps":"(47.0239,15.2679)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 Direct Sampling SDR.",
        "loc":"Graz, Austria",
        "sw_version":"UberSDR",
        "antenna":"active loop",
        "snr":"30,30",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Wartmannstetten, Austria",
        "url":"https://oe3gbb-1.tunnel.ubersdr.org/?freq=1000000&mode=am&bwl=-5000&bwh=5000&zoom_freq=1000000&zoom_bw=100.0",
        "gps":"(47.6921,16.0695)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 Direct Sampling SDR.",
        "loc":"Wartmannstetten, Austria",
        "sw_version":"UberSDR",
        "antenna":"terminated delta loop",
        "snr":"30,30",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"MF/HF WEBSDR, Santa Clarita CA, USA",
        "url":"http://kj6eo.com:8901/?tune=640am",
        "gps":"(34.4583,-118.5833)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Santa Clarita CA, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Washington DC, USA",
        "url":"http://na5b.com:8080/?freq=1120000&mode=am&bwl=-5000&bwh=5000&zoom_freq=1120000&zoom_bw=100.0",
        "gps":"(38.7666,-077.2148)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 Direct Sampling SDR.",
        "loc":"Washington DC, USA",
        "sw_version":"UberSDR",
        "antenna":"Various.",
        "snr":"27,27",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF WEBSDR, Washington DC, USA",
        "url":"http://na5b.com:8901/?tune=1120am",
        "gps":"(38.7500,-077.2500)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Washington DC, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"VHF WEBSDR, Washington DC, USA",
        "url":"http://na5b.com:8902/?tune=119100am",
        "gps":"(38.7500,-077.1667)",
        "bands":"118000000-137000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Washington DC, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Warrenton, VA, USA",
        "url":"https://ubersdr.k1ra.us:9443/?freq=1000000&mode=am&bwl=-5000&bwh=5000&zoom_freq=1000000&zoom_bw=100.0",
        "gps":"(38.7423,-077.7980)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 Direct Sampling SDR.",
        "loc":"Warrenton, VA, USA",
        "sw_version":"UberSDR",
        "antenna":"EFHW",
        "snr":"27,27",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Houston, TX, USA",
        "url":"https://k5jbt.tunnel.ubersdr.org/?freq=1000000&mode=am&bwl=-5000&bwh=5000&zoom_freq=1000000&zoom_bw=100.0",
        "gps":"(29.7840,-095.7200)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 Direct Sampling SDR.",
        "loc":"Houston, TX, USA",
        "sw_version":"UberSDR",
        "antenna":"EFHW",
        "snr":"27,27",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF Wideband NovaSDR, Dahlonega, GA, USA",
        "url":"http://websdr.lumpkinschools.com/?frequency=10000000&modulation=AM",
        "gps":"(34.5417,-084.0000)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 mk2",
        "loc":"Dahlonega, GA, USA",
        "sw_version":"NovaSDR",
        "antenna":"Multiband dipole",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"OpenWebRX, New Orleans, LA, USA",
        "url":"http://kb5avy.hopto.org:8073/#freq=870000,mod=am,sql=-150",
        "gps":"(30.0000,-090.1667)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various OpenWebRX quadrature sampling sources.",
        "loc":"New Orleans, LA, USA",
        "sw_version":"OpenWebRX",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"OpenWebRX, Las Vegas, NV, USA",
        "url":"https://websdr.kj7abk.com/#freq=840000,mod=am,sql=-150",
        "gps":"(36.0000,-115.2500)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various OpenWebRX quadrature sampling sources.",
        "loc":"Las Vegas, NV, USA",
        "sw_version":"OpenWebRX",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF UberSDR, Milford, PA, USA",
        "url":"http://novasdr.k3fef.com:9002/?frequency=10000000&modulation=AM",
        "gps":"(41.2417,-075.0500)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"RX-888 mk2",
        "loc":"Milford, PA, USA",
        "sw_version":"UberSDR",
        "antenna":"Various.",
        "snr":"30,30",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"OpenWebRX, Pittsburgh, PA, USA",
        "url":"https://hf.kevinheaven.net/#freq=1020000,mod=am,sql=-150",
        "gps":"(40.4167,-080.2500)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various OpenWebRX quadrature sampling sources.",
        "loc":"Pittsburgh, PA, USA",
        "sw_version":"OpenWebRX",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"MF/HF WEBSDR, Gatesville, TX, USA",
        "url":"http://sdr.kf5jmd.com:8901/?tune=900am",
        "gps":"(31.4167,-97.7500)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Gatesville, TX, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"LF/MF/HF WEBSDR (Yellow), Corinne, UT, USA",
        "url":"http://websdr1.sdrutah.org:8901/index1a.html?tune=1160sam-u",
        "gps":"(41.5833,-112.3333)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Corinne, UT, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"HF/VHF WEBSDR (Green), Corinne, UT, USA",
        "url":"http://websdr2.sdrutah.org:8902/index1a.html?tune=10000sam-u",
        "gps":"(41.5833,-112.2333)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Corinne, UT, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"HF/VHF WEBSDR (Blue), Corinne, UT, USA",
        "url":"http://websdr3.sdrutah.org:8903/index1a.html?tune=8992usb",
        "gps":"(41.5433,-112.3333)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Corinne, UT, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"HF WEBSDR (Magenta), Corinne, UT, USA",
        "url":"http://websdr4.sdrutah.org:8904/index1a.html?tune=14300usb",
        "gps":"(41.5433,-112.2333)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Corinne, UT, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"HF WEBSDR (Teal), Corinne, UT, USA",
        "url":"http://websdr5.sdrutah.org:8905/index1a.html?tune=13830sam-u",
        "gps":"(41.5433,-112.4333)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Corinne, UT, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
    {
        "name":"VHF WEBSDR (Peach), Corinne, UT, USA",
        "url":"http://slc2meters.sdrutah.org:8901/?tune=121500am?squelch=1",
        "gps":"(41.5833,-112.4333)",
        "bands":"0-30000000",
        "users_max":"800",
        "sdr_hw":"Various WebSDR quadrature sampling sources.",
        "loc":"Corinne, UT, USA",
        "sw_version":"WebSDR",
        "antenna":"Various.",
        "snr":"19,19",
        "status":"active",
        "offline":"no",
        "users":"0",
    },
]
;
